### PR TITLE
add support to 0.25, fix kiddkai/react-native-gestures#16

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by sibelius** [comment]
@kiddkai could you please review this and release another version?

**Comment by niftylettuce** [comment]
+1

**Comment by kiddkai** [comment]
Hi @sibeliusseraphini ,

Sorry for the late response and thank you for contributing this repo. Can you fixes the travis error which make sure that the build is passing?

```
> react-native-gestures@0.2.0 test /home/travis/build/kiddkai/react-native-gestures
> standard src/*.js && mocha --compilers js:babel/register --recursive --require should
standard: Use JavaScript Standard Style (https://github.com/feross/standard) 
  /home/travis/build/kiddkai/react-native-gestures/src/GestureView.js:4:12: Unexpected trailing comma.
  /home/travis/build/kiddkai/react-native-gestures/src/GestureView.js:5:15: Extra semicolon.
```

**Comment by sibelius** [comment]
fixed

**Comment by sibelius** [comment]
what do u think of this issue https://github.com/kiddkai/react-native-gestures/issues/18?

**Pull request merged**
