### PR TITLE
Refactor to use modern RN practices

### PR DESCRIPTION
**Pull request by assertchris**
~~**Please note: I am still adding things to this before I consider it ready for merge. I am submitting the pull request before then, so that you have more time to look over it and tell me whether or not you'd consider the merge.**~~

❤️  your work!

This pull request adds the following:

- Include the Yarn lock file
- Use Jest for testing + add new tests
- Use Prettier for automatic formatting (hooks included)
- Use ES6 component classes
- Use higher-order components instead of mixins
- Use PropTypes instead of React.PropTypes
- Drop support for image type (just wrap an Image component by hand)
- Rearrange base import to group Decorators, Gestures, and Responders

(about 4,400 additional lines are due to the Yarn lock file)

### CODE REVIEW

**Comment by assertchris** [comment]
Ok. I'm done with the refactor, pending any suggestions or merge requirements. Here's a demo of what it looks like (in a sample application):

demo

**Comment by assertchris** [comment]
Here's a story explaining how and why I made these changes: https://medium.com/over-engineering/refactoring-react-native-libraries-caefe13b6517

**Comment by jallynme** [comment]
can we merge this please

**Comment by assertchris** [comment]
I have simplified the design considerably, by removing the HoC/decorators and putting everything in GestureView. I'll explain why in an edit to the linked article.

**Comment by assertchris** [comment]
Hey there. Just checking in to see if there's anything I can do to help move this pull request along. 😸

**Comment by joaovpmamede** [comment]
This would really help a lot of people.

**Comment by assertchris** [comment]
5 years is a heck of long time. Good luck and thanks for all the fish!

**Pull request closed without merging**
